"use client";

/**
 * Client component rendered on the public /d/[slug] page.
 *
 * On mount it calls /api/d/[slug] to:
 *   1. Record the click (with UTM, referrer, UA).
 *   2. Get the correct WhatsApp URL (after weighted round-robin assignment).
 *   3. Redirect the visitor to WhatsApp.
 *
 * Because this runs after JavaScript executes, bots never reach this code.
 * Bots only see the static HTML + og: metadata generated by the Server Component.
 */

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ExternalLink, Loader2, MessageCircle, AlertTriangle } from "lucide-react";

interface Props {
  slug: string;
  name: string;
  seoDescription?: string | null;
  /** Uploaded OG / marketing image (shown at natural square size on the page) */
  ogImage?: string | null;
  isDraft?: boolean;
}

type State =
  | { phase: "loading" }
  | { phase: "redirecting"; waUrl: string; assignedName: string | null }
  | { phase: "error"; message: string }
  | { phase: "no_members" };

export function DirectLinkRedirectView({
  slug,
  name,
  seoDescription,
  ogImage,
  isDraft,
}: Props) {
  const searchParams = useSearchParams();
  const [state, setState] = useState<State>(
    isDraft ? { phase: "error", message: "draft-preview" } : { phase: "loading" }
  );
  const [imgFailed, setImgFailed] = useState(false);

  useEffect(() => {
    if (isDraft) return;

    async function fetchAndRedirect() {
      try {
        const qs = new URLSearchParams();
        ["utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term"].forEach((k) => {
          const v = searchParams.get(k);
          if (v) qs.set(k, v);
        });

        const apiUrl = `/api/d/${slug}${qs.toString() ? `?${qs.toString()}` : ""}`;
        const res = await fetch(apiUrl, { method: "GET" });
        const data = await res.json() as {
          wa_url?: string;
          assigned_name?: string;
          is_bot?: boolean;
          error?: string;
          redirect_status?: string;
        };

        if (data.is_bot) {
          setState({ phase: "error", message: "Preview mode — no redirect for bots." });
          return;
        }

        if (data.redirect_status === "no_members") {
          setState({ phase: "no_members" });
          return;
        }

        if (!res.ok || !data.wa_url) {
          setState({
            phase: "error",
            message: data.error ?? "This link is currently unavailable.",
          });
          return;
        }

        setState({
          phase: "redirecting",
          waUrl: data.wa_url,
          assignedName: data.assigned_name ?? null,
        });

        // Slightly longer delay so visitors can see the uploaded image
        const timer = window.setTimeout(() => {
          window.location.assign(data.wa_url!);
        }, 900);
        return () => window.clearTimeout(timer);
      } catch {
        setState({ phase: "error", message: "Something went wrong. Please try again." });
      }
    }

    void fetchAndRedirect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  const showHeroImage = Boolean(ogImage) && !imgFailed;
  const isBusy = state.phase === "loading" || state.phase === "redirecting";
  const isProblem = state.phase === "no_members" || state.phase === "error";

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-bg px-4 py-10">
      <div className="w-full max-w-sm space-y-5 text-center">

        {/* Hero: uploaded OG image at full square size (1000×1000 source) */}
        {showHeroImage ? (
          <div className="mx-auto w-full overflow-hidden rounded-2xl border border-border bg-muted shadow-sm">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={ogImage!}
              alt={name}
              width={1000}
              height={1000}
              className="aspect-square h-auto w-full object-cover"
              onError={() => setImgFailed(true)}
            />
          </div>
        ) : (
          <div className="flex justify-center">
            {isBusy ? (
              <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#25D366]/10 text-[#25D366]">
                <MessageCircle className="h-7 w-7" />
              </div>
            ) : isProblem ? (
              <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-500/10 text-amber-500">
                <AlertTriangle className="h-7 w-7" />
              </div>
            ) : null}
          </div>
        )}

        <div>
          <h1 className="text-xl font-bold text-fg">{name}</h1>
          {seoDescription && (
            <p className="mt-1 text-sm text-muted-fg">{seoDescription}</p>
          )}
        </div>

        {isBusy && (
          <div className="space-y-4">
            <div className="flex items-center justify-center gap-2 text-sm text-muted-fg">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span>Opening WhatsApp…</span>
            </div>

            {state.phase === "redirecting" && (
              <a
                href={state.waUrl}
                className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#25D366] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#22bf5b] active:scale-[0.98]"
              >
                <ExternalLink className="h-4 w-4" />
                {state.assignedName
                  ? `Chat with ${state.assignedName}`
                  : "Open WhatsApp"}
              </a>
            )}
          </div>
        )}

        {state.phase === "no_members" && (
          <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 px-5 py-4">
            <p className="text-sm font-medium text-amber-700 dark:text-amber-400">
              This link has no active WhatsApp recipients yet.
            </p>
            <p className="mt-1 text-xs text-amber-600 dark:text-amber-500">
              Please contact the link owner.
            </p>
          </div>
        )}

        {state.phase === "error" && state.message === "draft-preview" ? (
          <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 px-5 py-4">
            <p className="text-sm font-medium text-amber-700 dark:text-amber-400">
              Publish this link to enable the WhatsApp redirect.
            </p>
            <p className="mt-1 text-xs text-amber-600 dark:text-amber-500">
              Go back to the editor and click <strong>Publish</strong>.
            </p>
          </div>
        ) : state.phase === "error" ? (
          <div className="rounded-xl border border-red-500/20 bg-red-500/5 px-5 py-4">
            <p className="text-sm font-medium text-red-700 dark:text-red-400">
              {state.message}
            </p>
          </div>
        ) : null}

        <p className="text-[11px] text-muted-fg/60">Powered by OneForm</p>
      </div>
    </div>
  );
}
